version: '2'

services:
    nginx:
        container_name: custom_nginx
        image: nginx:latest
        restart: always
        ports:
            - "${HOST_NGINX_PORT}:80"
#            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./:/var/www
            - ./logs:/var/log/nginx
        links:
            - php
        networks:
          - internal_network_1

    php:
        container_name: custom_php
        build: ./images/php

        restart: always
        links:
            - mariadb
            - rabbitmq
        depends_on:
            - mariadb
            - rabbitmq
        volumes:
            - ./:/var/www
        networks:
          - internal_network_1

    mariadb:
        container_name: custom_mariadb
        image: mariadb:10.4
        restart: always
        ports:
            - "${HOST_MYSQL_PORT}:3306"
        volumes:
            - ./mariadb:/var/lib/mysql
        environment:
            MYSQL_DATABASE: "${MARIADB_DATABASE}"
            MYSQL_USER: "${MARIADB_USER}"
            MYSQL_PASSWORD: "${MARIADB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
        networks:
          - internal_network_1

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        volumes:
            - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
            - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
            - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - internal_network_1

    phpmyadmin:
        container_name: custom_phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "${HOST_PHPMYADMIN_PORT}:80"
        links:
            - mariadb:db
        depends_on:
            - mariadb
        environment:
            PMA_HOST: mariadb
            MYSQL_USER_NAME: root
            MYSQL_ROOT_PASSWORD: "mysql"
        networks:
            - internal_network_1

networks:
  internal_network_1:
    driver: bridge
